[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "auto-llama"
version = "0.0.1"
description = "Supercharge your local LLM with different agents"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["AI", "LLM", "Llama"]
authors = [
  { name = "LufixSch" }
]
classifiers = [
   "Programming Language :: Python :: 3",
   "Development Status :: 3 - Alpha",
   "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
   "Operating System :: OS Independent",
]

[project.optional-dependencies]
research = [
  "wikipedia",
  "duckduckgo_search"
]
code = [
  "docker"
]
memory = [
  "txtai",
  "nltk",
  "num2words"
]