FROM node:lts-alpine as base

ENV DATA_PATH="data"
ENV PUBLIC_OPEN_AI_ENDPOINT="http://127.0.0.1:5000/v1"
ENV PUBLIC_OPEN_AI_KEY="sk-11111111111111111111111111"
ENV ORIGIN="http://127.0.0.1:3000"
ENV SECRET="secret"

WORKDIR /app


FROM base as install

COPY ./package.json ./package.json
RUN npm install

COPY . .
RUN npm run build


FROM base as final

COPY --from=install /app/build /app/package.json ./
RUN npm install --omit=dev

ENTRYPOINT ["node", "."]
EXPOSE 3000
